### ISSUE TITLE
Consider reading auth-token from `.netrc`

### ISSUE THREAD

**Issue by friism** [bradledbetter/grunt-heroku-build-api#1]

**Comment by bradledbetter** [comment]
OK, considering it. 
I'm thinking of using https://github.com/heroku/heroku-auth-finder, then falling back to the Grunt options, then erroring out completely if all else fails.

Any opinions or helpful suggestions?

**Comment by friism** [comment]
Ah, you should be fine then - sorry.

**Comment by bradledbetter** [comment]
Oh, don't get me wrong - I wasn't considering it until you brought it up. Thanks for the suggestion.
