### ISSUE TITLE
Publish latest version to NPMJS

### ISSUE THREAD

**Issue by tnarik** [bradledbetter/grunt-heroku-build-api#2]
I was testing your plugin, which works really great, and it is a pity is not available in the NPM registry.

**Comment by bradledbetter** [comment]
https://www.npmjs.com/package/grunt-heroku-build-api

**Comment by tnarik** [comment]
Isn't the latest release 0.2.2?

**Comment by bradledbetter** [comment]
So it is. Must have forgotten to update. Many times over. :) It's updated now.
